### ISSUE TITLE
Unsupported Return Handling result: "RETURN_ITEM_LOST"

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#10]
In HandlingResult.php line 92:
                                              
  [InvalidArgumentException]                  
  Unknown enum value given: RETURN_ITEM_LOST  
                                              

Exception trace:
 () at /app/vendor/bol-com/retailer-api/src/Model/Rma/HandlingResult.php:92
 BolCom\RetailerApi\Model\Rma\HandlingResult::fromValue() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReducedReturnItem.php:221
 BolCom\RetailerApi\Model\Rma\ReducedReturnItem::fromArray() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReturnItemList.php:53
 BolCom\RetailerApi\Model\Rma\ReturnItemList::fromArray() at app/vendor/bol-com/retailer-api/src/Handler/Rma/GetAllReturnsHandler.php:54
 BolCom\RetailerApi\Handler\Rma\GetAllReturnsHandler->__invoke() at app/vendor/bol-com/retailer-api/src/Infrastructure/MessageBus.php:111
 BolCom\RetailerApi\Infrastructure\MessageBus->dispatch() at app/src/BolCom/ReturnsService.php:37

**Comment by JeroenVanLeusden** [comment]
See #11
