### ISSUE TITLE
GetShipment: Key 'surname' is missing in data array or is not a string 

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#17]
Data example: 
```
Array
(
    [shipmentId] => XXXXX
    [shipmentDate] => 2019-08-25T22:04:27+02:00
    [shipmentReference] => XXXXX
    [shipmentItems] => Array
        (
            [0] => Array
                (
                    [orderItemId] => XXXXX
                    [orderId] => XXXXX
                    [orderDate] => 2019-08-25T20:06:12+02:00
                    [latestDeliveryDate] => 2019-08-26
                    [ean] => XXXXX
                    [title] => XXXXX
                    [quantity] => 1
                    [offerPrice] => 36.99
                    [offerCondition] => NEW
                    [offerReference] => XXXXX
                    [fulfilmentMethod] => FBB
                )

        )

    [transport] => Array
        (
            [transportId] => XXXXX
            [transporterCode] => TNT
            [trackAndTrace] => XXXXX
        )

    [customerDetails] => Array
        (
            [salutationCode] => 03
            [zipCode] => 2541CD
            [countryCode] => NL
        )

)
```

In CustomerDetails.php line 217:
                                                             
  [InvalidArgumentException]                                 
  Key 'surname' is missing in data array or is not a string  
                                                             

Exception trace:
 () at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/Customer/CustomerDetails.php:217
 BolCom\RetailerApi\Model\Customer\CustomerDetails::fromArray() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/Shipment/Shipment.php:166
 BolCom\RetailerApi\Model\Shipment\Shipment::fromArray() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Handler/Shipment/GetShipmentHandler.php:46
 BolCom\RetailerApi\Handler\Shipment\GetShipmentHandler->__invoke() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Infrastructure/MessageBus.php:111

**Comment by JeroenVanLeusden** [comment]
Is `surname` the only missing key in `CustomerDetails `?

**Comment by JeroenVanLeusden** [comment]
Fied in 2e2ddf3828f1a85435a3a7b15c56981d0d9b0ccb
