### ISSUE TITLE
GetShipmentList:  Value "2019-11-11T08:35:19.547+01:00" is not a valid ISO 8601 format.

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#19]
I suppose It makes sense support that date time format in all API methods.

`In Assertion.php line 2752:
                                                                         
  [Assert\InvalidArgumentException (214)]                                
  Value "2019-11-11T08:35:19.547+01:00" is not a valid ISO 8601 format.  
                                                                         

Exception trace:
 () at /var/www/projects/bol.com-app/vendor/beberlei/assert/lib/Assert/Assertion.php:2752
 Assert\Assertion::createException() at /var/www/projects/bol.com-app/vendor/beberlei/assert/lib/Assert/Assertion.php:2403
 Assert\Assertion::date() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/DateTime.php:17
 BolCom\RetailerApi\Model\DateTime->__construct() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/DateTime.php:31
 BolCom\RetailerApi\Model\DateTime::fromString() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/Shipment/ShipmentListItem.php:111
 BolCom\RetailerApi\Model\Shipment\ShipmentListItem::fromArray() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Model/Shipment/ShipmentList.php:53
 BolCom\RetailerApi\Model\Shipment\ShipmentList::fromArray() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Handler/Shipment/GetShipmentListHandler.php:54
 BolCom\RetailerApi\Handler\Shipment\GetShipmentListHandler->__invoke() at /var/www/projects/bol.com-app/vendor/bol-com/retailer-api/src/Infrastructure/MessageBus.php:111
`

**Comment by JeroenVanLeusden** [comment]
@DangerLifter I've contacted bol.com for this because they claim to use SO 8601 but clearly they're not consistently. For now i've converted the date to SO 8601.
