### ISSUE TITLE
Enabling testmode

### ISSUE THREAD

**Issue by petervanackooij** [ho-nl/BolCom_RetailerApi#2]
Hi,

I figured out that setting the api to testmode can be done by adding the $clientUrl to the ClientConfig constructor. Works fine, but as a user of the package I really don't care about the urls, I just want to enable or disable testmode. 

I see two solutions to this enhancement: 

1: You're doing such a great job putting everything in constants, let's put these url's in constants as well, so I can grab them when needed.

2: My favourite and it extends solution 1: Change the constructor in ClientConfig and replace the $clientUrl parameter with $testMode. The $testMode boolean will decide witch of the two urls to use.

**Comment by JeroenVanLeusden** [comment]
I'll add it to the backlog, bol.com will determine when this will be implemented. I can't tell you when exactly.

**Comment by JeroenVanLeusden** [comment]
@petervanackooij It's implemented in cda113968f881a6a2b59f619264fd9f5f7e775a5.
