### ISSUE TITLE
Undefined class constant 'DC34d'

### ISSUE THREAD

**Issue by xf039** [ho-nl/BolCom_RetailerApi#26]
Delivery date constant DC34d is no longer defined in:
https://github.com/ho-nl/BolCom_RetailerApi/blob/master/src/Model/Offer/DeliveryCode.php#L48

Your Magento plugin is using this constant. (ho-nl/bol-com-retailer).

Model/Config/Source/DeliveryCode.php:33
\BolCom\RetailerApi\Model\Offer\DeliveryCode::DC34d

**Comment by JeroenVanLeusden** [comment]
You're right, we've released v1.0.4 of ho-nl/bol-com-retailer to force the usage of v1.0 of this package. The 3-4 days options is no longer supported by bol.com though so you should avoid using it.

**Comment by Wiseconn-SB** [comment]
The requested package honl/bol-com-retailer 1.0.4 exists as honl/bol-com-retailer[1.0.3, 1.0.2, 1.0.1, 1.0.0] 

Could you please release version 1.0.4? 1.0.3 is breaking the indexing.

**Comment by JeroenVanLeusden** [comment]
v1.0.4 is released to the marketplace on March 5th (https://marketplace.magento.com/honl-bol-com-retailer.html).

**Comment by Wiseconn-SB** [comment]
JeroenvanLeusden,
Thank you for your reply. I understand that we should not use composer anymore for this plugin?

**Comment by Wiseconn-SB** [comment]
I found the problem. For anyone experiencing the same issue even after updating:
The update 1.0.4. does not update the attributes. So the attribute with code bol_delivery_code still has the source model BolCom\Retailer\Model\Config\Source\DeliveryCode. Remove this from the database row and indexing will work again. Uninstalling the previous version before installing version 1.0.4 does not remove the source model from the attribute.

**Comment by nocturnalfrog** [comment]
This problem also occurs on a fresh install!
Please fix this.
