### ISSUE TITLE
purchasable-shippinglabels not possible?

### ISSUE THREAD

**Issue by internetboekhandel** [ho-nl/BolCom_RetailerApi#27]
To be able to make a shippinglabel from bol we need the list of available shipping labes with their corresponding shippingLabelCode. I cannot see this option:
The shippingLabelCode is not always the same and can en will change, so we need this option.

purchasable-shippinglabels

Should generate somehting like:
{
  "purchasableShippingLabels" : [ {
    "transporterCode" : "DHLFORYOU",
    "labelType" : "PARCEL",
    "maxWeight" : "10 kg",
    "maxDimensions" : "80 x 40 x 18,75 cm",
    "retailerPrice" : 6.0,
    "purchasePrice" : 4.83,
    "discount" : 2.38,
    "shippingLabelCode" : "PLR00000002"
  }, {
    "transporterCode" : "TNT",
    "labelType" : "PARCEL",
    "maxWeight" : "2 kg",
    "maxDimensions" : "38 x 26,5 x 3,2 cm",
    "retailerPrice" : 5.5,
    "purchasePrice" : 4.22,
    "discount" : 0.51,
    "shippingLabelCode" : "PLR00000011"
  }, {
    "transporterCode" : "DPD-NL",
    "labelType" : "PARCEL",
    "maxWeight" : "20 kg",
    "maxDimensions" : "100 x 50 x 50 cm",
    "retailerPrice" : 6.5,
    "purchasePrice" : 6.39,
    "discount" : 2.63,
    "shippingLabelCode" : "PLR00000014"
  } ]
}

**Comment by JeroenVanLeusden** [comment]
You should be able to fetch that using:

```PHP
/** @var \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelList $shippingLabelList */
$shippingLabelList = $messageBus->dispatch(\BolCom\RetailerApi\Model\ShippingLabel\Query\GetShippingLabels::with(
    \BolCom\RetailerApi\Model\Order\OrderItemId::fromString('6107434013')
));
