### ISSUE TITLE
get offerid for offer update

### ISSUE THREAD

**Issue by youasl** [ho-nl/BolCom_RetailerApi#34]
In api v2 if you want to update an offer it could be done easily. The offers are uniquely identified by the combination of EAN+Condition.

In this api version (v3) you need an offer-id for a offer update / delete.
So my question is, how can I easily update an offer, like in v2, with for example only EAN or Reference? My guess is this is not possible.

So the question is: how can you push an update without needing the export file or creating a database which contains all the offer-id's? Take into account the you can only ask 10 export files in an hour, due to limits.

**Comment by JeroenVanLeusden** [comment]
You can't, an offer-id is needed to update an offer.

**Comment by youasl** [comment]
Alright, then the next problem occures:
The only way to retrieve offer id's, is through the export file. Retrieving an exportfile is not directly and is going as a 'job' with 'PENDING' status. That means you will never get the exportfile until you do another request (process-status) to see if the job is done, which give the status 'SUCCESS'.

So in order to get the offer-id's. I need to spam check until the process status is 'SUCCES' then I can update the offers.

Can you please tell me how you guys handle this?

**Comment by JeroenVanLeusden** [comment]
Exactly, we've implemented it the same way. We save the offer id's in a database table for future usage.
