### ISSUE TITLE
Feature request: set custom price for Bol.com

### ISSUE THREAD

**Issue by jghaanstra** [ho-nl/BolCom_RetailerApi#37]
I'd like the see an option where you can set the a custom product price for Bol.com seperatly from the Magento catalog price. This is useful to compensate for the Bol.com fees.

**Comment by JeroenVanLeusden** [comment]
This package has nothing to do with the Magento module itself. You can simply change the numbers in your call to send a different price to bol.com

```php
/** @var \BolCom\RetailerApi\Model\ProcessStatus\ProcessStatus $processStatus */
$processStatus = $messageBus->dispatch(\BolCom\RetailerApi\Model\Offer\Command\UpdateOfferPrice::with(
    \BolCom\RetailerApi\Model\Offer\OfferId::fromString('6ff736b5-cdd0-4150-8c67-78269ee986f5'),
    \BolCom\RetailerApi\Model\Offer\Pricing::fromArray([
        'bundlePrices' => [
            ['quantity' => 1, 'price' => 12]
            ['quantity' => 10, 'price' => 10]
        ]
    ])
));
```

If you are referring to the Magento 2 module. I can't help you with that, officially you are not allowed to add a fee other than the shipping costs to you prices. You'll have to implement this yourself if needed.
