### ISSUE TITLE
ShipOrderItem::with

### ISSUE THREAD

**Issue by ShockRaver** [ho-nl/BolCom_RetailerApi#39]
Hi,

In your example of ShipOrderItem:

`/** @var \BolCom\RetailerApi\Model\ProcessStatus\ProcessStatus $processStatus */
$processStatus = $messageBus->dispatch(\BolCom\RetailerApi\Model\Order\Command\ShipOrderItem::with(
    \BolCom\RetailerApi\Model\Order\OrderItemId::fromString('6107434013'),
    'Shipment Reference',
    null,
    \BolCom\RetailerApi\Model\Transport\TransportInstruction::fromArray([
        'transporterCode' => 'TNT',
        'trackAndTrace' => '123456789'
    ])
));`

PHPSTORM is telling me:
Method call is provided 4 parameters, but the method signature uses 3 parameters

So actually the ShipOrderItem isn't doing anything with the Transportinstructions. And Bol.com doesn't get the transportCode and Track&Trace info.

I then need to update the shipment ID with a PUT to /retailer/transports/123456 with the TransportCode and Track&trace, only then the correct info is added to the Bol order.

Is that how its supposed to work? Or should the track&trace info be added to the order directly?

**Comment by JeroenVanLeusden** [comment]
@ShockRaver Missed this when we removed the ability to purchase shipping labels. You should use:
```PHP
/** @var \BolCom\RetailerApi\Model\ProcessStatus\ProcessStatus $processStatus */
$processStatus = $messageBus->dispatch(\BolCom\RetailerApi\Model\Order\Command\ShipOrderItem::with(
    \BolCom\RetailerApi\Model\Order\OrderItemId::fromString('6107434013'),
    'Shipment Reference',
    \BolCom\RetailerApi\Model\Transport\TransportInstruction::fromArray([
        'transporterCode' => 'TNT',
        'trackAndTrace' => '123456789'
    ])
));
```
