### ISSUE TITLE
Php 7.4.19

### ISSUE THREAD

**Issue by tsukasa1989** [ho-nl/BolCom_RetailerApi#43]
Currently Magento 2.3.7 or 2.4.x PHP 7.4 is required.

I have had to disable this module because it is not compatible with the PHP version and does give serious errors when ran on 7.4. But now I have disabled this module I get errors on the product pages in the admin that `Class BolCom\Retailer\Model\Config\Soure\PublishStatus does not exist`.

Is there an expectation when it's compatible with 7.4 or how to resolve the issue above?

**Comment by JeroenVanLeusden** [comment]
@tsukasa1989,

This package is compatible with PHP7.4. If you have specific questions regarding the Magento 2 module please contact [younify](https://www.younify.nl/magento-bol/).

**Comment by tsukasa1989** [comment]
Not true if you install it via Composer I get the following message:

`Package honl/bol-com-retailer at version  has a PHP requirement incompatible with your PHP version (7.4.19)`
