### ISSUE TITLE
Shipping method configuration with table rate condition "Weight vs Destination" not working

### ISSUE THREAD

**Issue by hardiksinh** [ho-nl/BolCom_RetailerApi#45]
We have in shipping method rate type "Table" is configured and at website level config table condition "Table vs. Destination" set. The table uploaded has different shipping prices based on weight and country location and zip code. But shipment creation always takes first price of table and ignores weight based price of shipping.

**Comment by JeroenVanLeusden** [comment]
This package has no knowledge of shipping methods in your system. If you referring to the magento 2 module please contact [younify](https://www.younify.nl/magento-bol/).
