### ISSUE TITLE
Support volume discount for pricing.bundlePrices

### ISSUE THREAD

**Issue by egogo-nl** [ho-nl/BolCom_RetailerApi#5]
Volume discount is now officially supported by the Bol.com Retailer API.
Any plans of implanting this in the package?

**Comment by JeroenVanLeusden** [comment]
It should work already, the `@todo`'s were there because it wasn't by the time this package was developed.

Are you experiencing issues using bundle prices?

**Comment by egogo-nl** [comment]
Yes, I'm experiencing issues. For example, when use this command:
```
// update offer price
$processStatus = $messageBus->dispatch(\BolCom\RetailerApi\Model\Offer\Command\UpdateOfferPrice::with(
  \BolCom\RetailerApi\Model\Offer\OfferId::fromString($strOfferId),
  \BolCom\RetailerApi\Model\Offer\Pricing::fromArray([
    'bundlePrices' => [
      ['quantity' => 1, 'price' => 20],
      ['quantity' => 2, 'price' => 39]
    ]
])), $arrBolAccount['account']);
```

I'm getting an exception:
```
`400 Bad request: `pricing.bundlePrices`: Collection should contain bundle price with prices in decreasing order (no duplicates).` response: (truncated...)
```

When I remove the second bundle price (with quantity 2), it's working. I also tried to change the order (first quantity 2, then quantity 1), but the same error.

**Comment by egogo-nl** [comment]
You are right, that was the problem. Sorry for this and thank you!
