### ISSUE TITLE
GetStatusByProcessIdsHandler class no longer uses concurrent requests

### ISSUE THREAD

**Issue by JeroenVanLeusden** [ho-nl/BolCom_RetailerApi#55]
In https://github.com/ho-nl/BolCom_RetailerApi/pull/54 a change is introduced, particularly [here](https://github.com/ho-nl/BolCom_RetailerApi/blob/master/src/Handler/ProcessStatus/GetStatusByProcessIdsHandler.php#L38) that results in the `GetStatusByProcessIdsHandler` no longer being able to handle concurrent requests.

Obviously i don't have access to the Magento module itself but you might want to check if this change is intentional and if so, refactor the method to no longer use promises or revert to support concurrent requests again.

**Comment by PascalBrouwers** [comment]
Thank you @JeroenVanLeusden 
Will be fixed in 4.0.3: https://github.com/ho-nl/BolCom_RetailerApi/pull/56
