### ISSUE TITLE
Get returns causes exception "Value is not a valid ISO 8601 format."

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#6]
On call "get returns' bol.com Api returns some dates in format "2019-05-15T17:09:38.137+02:00" which causes Assert\InvalidArgumentException: Value is not a valid ISO 8601 format.
Problem with milliseconds part in date time string.

Here is final stack in one of my cases:

 () at app/vendor/beberlei/assert/lib/Assert/Assertion.php:2752
 Assert\Assertion::createException() at app/vendor/beberlei/assert/lib/Assert/Assertion.php:2403
 Assert\Assertion::date() at app/vendor/bol-com/retailer-api/src/Model/DateTime.php:16
 BolCom\RetailerApi\Model\DateTime->__construct() at app/vendor/bol-com/retailer-api/src/Model/DateTime.php:30
 BolCom\RetailerApi\Model\DateTime::fromString() at app/src/Command/Returns/ImportCommand.php:37

**And one more similar place:**

In Assertion.php line 2752:
                                           
  [Assert\InvalidArgumentException (214)]  
  Value is not a valid ISO 8601 format.    
                                           

Exception trace:
 () at app/vendor/beberlei/assert/lib/Assert/Assertion.php:2752
 Assert\Assertion::createException() at app/vendor/beberlei/assert/lib/Assert/Assertion.php:2403
 Assert\Assertion::date() at pp/vendor/bol-com/retailer-api/src/Model/DateTime.php:19
 BolCom\RetailerApi\Model\DateTime->__construct() at app/vendor/bol-com/retailer-api/src/Model/DateTime.php:33
 BolCom\RetailerApi\Model\DateTime::fromString() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReducedReturnItem.php:243
 BolCom\RetailerApi\Model\Rma\ReducedReturnItem::fromArray() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReturnItemList.php:53
 BolCom\RetailerApi\Model\Rma\ReturnItemList::fromArray() at app/vendor/bol-com/retailer-api/src/Handler/Rma/GetAllReturnsHandler.php:54
 BolCom\RetailerApi\Handler\Rma\GetAllReturnsHandler->__invoke() at app/vendor/bol-com/retailer-api/src/Infrastructure/MessageBus.php:111

**Comment by JeroenVanLeusden** [comment]
@DangerLifter Dates should be converted already in https://github.com/ho-nl/BolCom_RetailerApi/blob/master/src/Handler/Rma/GetAllReturnsHandler.php#L50-L51

Are you able to create a failing test for this?

**Comment by DangerLifter** [comment]
Handler processes "registrationDateTime" but with "processingDateTime"
