### ISSUE TITLE
Unsupported Return Handling result: "FAILED_TO_COLLECT_BY_TRANSPORTER"

### ISSUE THREAD

**Issue by DangerLifter** [ho-nl/BolCom_RetailerApi#8]
app/vendor/bol-com/retailer-api/src/Model/Rma/ReducedReturnItem.php:220:
string(32) "FAILED_TO_COLLECT_BY_TRANSPORTER"

In HandlingResult.php line 85:
                              
  [InvalidArgumentException]  
  Unknown enum value given    
                              

Exception trace:
 () at app/vendor/bol-com/retailer-api/src/Model/Rma/HandlingResult.php:85
 BolCom\RetailerApi\Model\Rma\HandlingResult::fromValue() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReducedReturnItem.php:221
 BolCom\RetailerApi\Model\Rma\ReducedReturnItem::fromArray() at app/vendor/bol-com/retailer-api/src/Model/Rma/ReturnItemList.php:53
 BolCom\RetailerApi\Model\Rma\ReturnItemList::fromArray() at app/vendor/bol-com/retailer-api/src/Handler/Rma/GetAllReturnsHandler.php:54
 BolCom\RetailerApi\Handler\Rma\GetAllReturnsHandler->__invoke() atapp/vendor/bol-com/retailer-api/src/Infrastructure/MessageBus.php:111

**Comment by JeroenVanLeusden** [comment]
@DangerLifter You sure this is a valid result? Because it's not listed by bol.com (https://developers.bol.com/apiv3returns/).

**Comment by DangerLifter** [comment]
Yes. Here it is response from bol.com production (return in our shop):
Array
(
    [rmaId] => XXXXXX
    [orderId] => XXXXXX
    [ean] => XXXXXX
    [quantity] => 1
    [registrationDateTime] => 2019-10-21T08:50:17+02:00
    [returnReason] => Verkeerde maat of formaat
    [returnReasonComments] => Zit voor geen meter
    [fulfilmentMethod] => FBB
    [handled] => 1
    [handlingResult] => FAILED_TO_COLLECT_BY_TRANSPORTER
    [processingResult] => CANCELLED
    [processingDateTime] => 2019-10-21T18:59:49.946+02:00
)
